import {Component} from 'angular2/core';
import {Http} from 'angular2/http';


@Component({
  selector: 'myOrders',
  templateUrl: 'app/components/myOrders/myOrders.html',
  styleUrls: ['app/components/myOrders/myOrders.css'],
  providers: [],
  directives: [],
  pipes: []
})
export class MyOrders {

  orders = [{companyName: 'Infosys',
    orderDetails: '5 Tissue boxes, 10 Hand dryers, 20 paper towels',
    orderDate: '03/24/2016',
    completionDate: '03/24/2016',
    status: 'In-Progress',
    orderType: 'email'},
    {companyName: 'HSBC',
      orderDetails: '5 Tissue boxes, 10 Hand dryers, 20 paper towels',
      orderDate: '02/10/2016',
      completionDate: '03/24/2016',
      status: 'Completed',
      orderType: 'online'},
    {companyName: 'IBM',
      orderDetails: '5 Tissue boxes, 10 Hand dryers, 20 paper towels',
      orderDate: '06/30/2016',
      completionDate: '03/24/2016',
      status: 'Completed',
      orderType: 'phone'},
    {companyName: 'Cognizant',
      orderDetails: '5 Tissue boxes, 10 Hand dryers, 20 paper towels',
      orderDate: '02/01/2016',
      completionDate: '03/24/2016',
      status: 'In-Progress',
      orderType: 'manual'},
    {companyName: 'Quick Heal',
      orderDetails: '5 Tissue boxes, 10 Hand dryers, 20 paper towels',
      orderDate: '02/20/2016',
      completionDate: '03/24/2016',
      status: 'Completed',
      orderType: 'email'},
    {companyName: 'Infosys',
      orderDetails: '5 Tissue boxes, 10 Hand dryers, 20 paper towels',
      orderDate: '03/24/2016',
      completionDate: '03/24/2016',
      status: 'In-Progress',
      orderType: 'email'},
    {companyName: 'HSBC',
      orderDetails: '5 Tissue boxes, 10 Hand dryers, 20 paper towels',
      orderDate: '02/10/2016',
      completionDate: '03/24/2016',
      status: 'In-Progress',
      orderType: 'online'},
    {companyName: 'IBM',
      orderDetails: '5 Tissue boxes, 10 Hand dryers, 20 paper towels',
      orderDate: '06/30/2016',
      completionDate: '03/24/2016',
      status: 'Completed',
      orderType: 'phone'}];

  allProducts =  [{productName: 'Dettol Hand wash', brand:'Dettol' ,Variant: '300 ml', availability: 'Yes'},
                  {productName: 'Dettol Hand wash', brand:'Dettol' ,Variant: '500 ml', availability: 'Yes'},
                  {productName: 'Dettol Hand wash', brand:'Dettol' ,Variant: '1 Ltr', availability: 'Yes'},
                  {productName: 'Tissue Papers', brand:'Hindusthan Lever' ,Variant: '100 Pcs', availability: 'No'},
                  {productName: 'Tissue Papers', brand:'Hindusthan Lever' ,Variant: '300 Pcs', availability: 'Yes'},
                  {productName: 'Dettol Antiseptic', brand:'Hindusthan Lever' ,Variant: '100 ml', availability: 'Yes'},
                  {productName: 'Dettol Antiseptic', brand:'Apple' ,Variant: '500 ml', availability: 'No'},
                  {productName: 'Toilet Paper', brand:'Orient' ,Variant: '50 Pcs', availability: 'Yes'},
                  {productName: 'Toilet Paper', brand:'Orient' ,Variant: '100 Pcs', availability: 'Yes'},
                  {productName: 'Toilet Paper', brand:'Orient' ,Variant: '500 Pcs', availability: 'No'},
                  {productName: 'Room Freshner', brand:'Orient' ,Variant: '300 ml', availability: 'Yes'},
                  {productName: 'Room Freshner', brand:'Hindusthan Lever' ,Variant: '300 ml', availability: 'Yes'},
                  {productName: 'Room Freshner', brand:'Hindusthan Lever' ,Variant: '300 ml', availability: 'No'},
                  {productName: 'Room Freshner', brand:'Hindusthan Lever' ,Variant: '300 ml', availability: 'Yes'},
                  {productName: 'Dettol Hand wash', brand:'Hindusthan Lever' ,Variant: '500 ml', availability: 'Yes'},
                  {productName: 'Dettol Hand wash', brand:'Hindusthan Lever' ,Variant: '1 Ltr', availability: 'Yes'},
                  {productName: 'Tissue Papers', brand:'Hindusthan Lever' ,Variant: '100 Pcs', availability: 'No'},
                  {productName: 'Tissue Papers', brand:'Hindusthan Lever' ,Variant: '300 Pcs', availability: 'Yes'},
                  {productName: 'Dettol Antiseptic', brand:'Hindusthan Lever' ,Variant: '100 ml', availability: 'Yes'},
                  {productName: 'Dettol Antiseptic', brand:'Hindusthan Lever' ,Variant: '500 ml', availability: 'No'},
                  {productName: 'Toilet Paper', brand:'Hindusthan Lever' ,Variant: '50 Pcs', availability: 'Yes'},
                  {productName: 'Toilet Paper', brand:'Hindusthan Lever' ,Variant: '100 Pcs', availability: 'Yes'},
                  {productName: 'Toilet Paper', brand:'Hindusthan Lever' ,Variant: '500 Pcs', availability: 'No'},
                  {productName: 'Room Freshner', brand:'Hindusthan Lever' ,Variant: '300 ml', availability: 'Yes'},
                  {productName: 'Room Freshner', brand:'Hindusthan Lever' ,Variant: '300 ml', availability: 'Yes'},
                  {productName: 'Room Freshner', brand:'Hindusthan Lever' ,Variant: '300 ml', availability: 'No'},
                  {productName: 'Room Freshner', brand:'Hindusthan Lever' ,Variant: '300 ml', availability: 'Yes'},
                  {productName: 'Dettol Hand wash', brand:'Hindusthan Lever' ,Variant: '500 ml', availability: 'Yes'},
                  {productName: 'Dettol Hand wash', brand:'Hindusthan Lever' ,Variant: '1 Ltr', availability: 'Yes'},
                  {productName: 'Tissue Papers', brand:'Hindusthan Lever' ,Variant: '100 Pcs', availability: 'No'},
                  {productName: 'Tissue Papers', brand:'Hindusthan Lever' ,Variant: '300 Pcs', availability: 'Yes'},
                  {productName: 'Dettol Antiseptic', brand:'Samsung' ,Variant: '100 ml', availability: 'Yes'},
                  {productName: 'Dettol Antiseptic', brand:'Hindusthan Lever' ,Variant: '500 ml', availability: 'No'},
                  {productName: 'Toilet Paper', brand:'Hindusthan Lever' ,Variant: '50 Pcs', availability: 'Yes'},
                  {productName: 'Toilet Paper', brand:'Orient' ,Variant: '100 Pcs', availability: 'Yes'},
                  {productName: 'Toilet Paper', brand:'Orient' ,Variant: '500 Pcs', availability: 'No'},
                  {productName: 'Room Freshner', brand:'Hindusthan Lever' ,Variant: '300 ml', availability: 'Yes'},
                  {productName: 'Room Freshner', brand:'Samsung' ,Variant: '300 ml', availability: 'Yes'},
                  {productName: 'Room Freshner', brand:'Samsung' ,Variant: '300 ml', availability: 'No'},
                  {productName: 'Room Freshner', brand:'Hindusthan Lever' ,Variant: '300 ml', availability: 'Yes'},
                  {productName: 'Dettol Hand wash', brand:'Hindusthan Lever' ,Variant: '500 ml', availability: 'Yes'},
                  {productName: 'Dettol Hand wash', brand:'Samsung' ,Variant: '1 Ltr', availability: 'Yes'},
                  {productName: 'Tissue Papers', brand:'Hindusthan Lever' ,Variant: '100 Pcs', availability: 'No'},
                  {productName: 'Tissue Papers', brand:'Hindusthan Lever' ,Variant: '300 Pcs', availability: 'Yes'},
                  {productName: 'Dettol Antiseptic', brand:'Hindusthan Lever' ,Variant: '100 ml', availability: 'Yes'},
                  {productName: 'Dettol Antiseptic', brand:'Hindusthan Lever' ,Variant: '500 ml', availability: 'No'},
                  {productName: 'Toilet Paper', brand:'Hindusthan Lever' ,Variant: '50 Pcs', availability: 'Yes'},
                  {productName: 'Toilet Paper', brand:'Hindusthan Lever' ,Variant: '100 Pcs', availability: 'Yes'},
                  {productName: 'Toilet Paper', brand:'Hindusthan Lever' ,Variant: '500 Pcs', availability: 'No'},
                  {productName: 'Room Freshner', brand:'Hindusthan Lever' ,Variant: '300 ml', availability: 'Yes'},
                  {productName: 'Room Freshner', brand:'Hindusthan Lever' ,Variant: '300 ml', availability: 'Yes'},
                  {productName: 'Room Freshner', brand:'Apple' ,Variant: '300 ml', availability: 'No'},
                  {productName: 'Room Freshner', brand:'Apple' ,Variant: '300 ml', availability: 'Yes'},
                  {productName: 'Dettol', brand:'Apple' ,Variant: '300 ml', availability: 'Yes'}];

  selectedItem: string;

  displayDetails(item) { this.selectedItem = item; }
}

